### ISSUE TITLE
Error when installing Ipopt on Mac

### ISSUE THREAD

**Issue by bwuzhang** [udacity/CarND-MPC-Project#25] opened 2018-04-14 22:06 UTC
Hi when I ran `  brew tap udacity/CarND-MPC-Project https://github.com/udacity/CarND-MPC-Project`
I got this. How to solve this?
```
==> Tapping udacity/carnd-mpc-project
Cloning into '/usr/local/Homebrew/Library/Taps/udacity/homebrew-carnd-mpc-project'...
remote: Counting objects: 1747, done.
remote: Compressing objects: 100% (1397/1397), done.
remote: Total 1747 (delta 294), reused 1738 (delta 294), pack-reused 0
Receiving objects: 100% (1747/1747), 2.46 MiB | 824.00 KiB/s, done.
Resolving deltas: 100% (294/294), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/udacity/homebrew-carnd-mpc-project/mumps.rb
Calling 'depends_on :mpi' is disabled!
Use 'depends_on "open-mpi"' instead.
/usr/local/Homebrew/Library/Taps/udacity/homebrew-carnd-mpc-project/mumps.rb:35:in `<class:Mumps>'
Please report this to the udacity/carnd-mpc-project tap!
Or, even better, submit a PR to fix it!
Error: Cannot tap udacity/carnd-mpc-project: invalid syntax in tap!
```

**Comment by Rdelux** [comment] 2018-04-15 13:50
I have exactly the same issue as well.  I think the issue is with the Mumps and Metis dependencies - I can't download them

**Comment by huynguyen** [comment] 2018-04-17 05:31
Dup of https://github.com/udacity/CarND-MPC-Project/issues/24

See my comment https://github.com/udacity/CarND-MPC-Project/issues/24#issuecomment-381848044 for a possible workaround.

**Comment by mvirgo** [comment] 2018-05-10 20:13
Closing since it's a duplicate of #24

**Closed as completed by mvirgo** 2018-05-10 20:13 UTC
